module FIPS
  VERSION: String

  type state_record = {
    fips: String,
    abbr: String,
    name: String,
    ansi: String
  }

  type county_record = {
    state_abbr: String,
    fips: String,
    gnis: String,
    name: String,
    class_code: String,
    status: String
  }

  type subdivision_record = {
    state_abbr: String,
    fips: String,
    county_name: String,
    gnis: String,
    name: String,
    class_code: String,
    status: String
  }

  type lookup_record = state_record | county_record | subdivision_record
  type database_row = Hash[String, untyped]

  class NotFoundError < StandardError
  end

  module Database
    DB_PATH: String

    def self.all: (String sql, ?Array[String] bind_vars) -> Array[database_row]
    def self.first: (String sql, ?Array[String] bind_vars) -> database_row?
  end

  def self.lookup: (?fips: String?, ?state: String?, ?county: String?, ?subdivision: String?) -> lookup_record

  class State
    def self.lookup: (?fips: String?, ?state: String?) -> state_record
    def self.state_abbr: (String code) -> String
    def self.all: () -> Array[state_record]
  end

  class County
    def self.lookup: (?fips: String?, ?state: String?, ?county: String?) -> county_record
    def self.all: (state: String state) -> Array[county_record]
  end

  class Subdivision
    def self.lookup: (?fips: String?, ?state: String?, ?county: String?, ?subdivision: String?) -> subdivision_record
    def self.all: (state: String state, ?county: String?) -> Array[subdivision_record]
  end
end
